---
title: "FSCI 2020: W24 Syllabus - Working with Scholarly Literature in R: Pulling, Wrangling, Cleaning, and Analyzing Structured Bibliographic Metadata."
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    css: styles.css
---

# Intro

Hello everyone. I'm looking forward to our session at [FSCI 2020](https://www.force11.org/fsci/2020) on ["W24 - Working with Scholarly Literature in R: Pulling, Wrangling, Cleaning, and Analyzing Structured Bibliographic Metadata."](https://www.force11.org/fsci/2020/fsci-2020-course-abstracts#W24) 

1. [Course Syllabus](fsci2020/fsci2020_syllabus.html)
2. [Setup Instructions](fsci2020/setup_instructions.html)
3. [Introduction to R](fsci2020/IntroductionToR.html)
4. [R Basics](fsci2020/RBasics.html)
5. [Data Exploration](fsci2020/DataExploration.html)
6. [Exploring Data in Lists](fsci2020/jennybc_lists_lesson.html)
7. [rcrossref](fsci2020/rcrossref.html)
8. [rorcid](fsci2020/rorcid.html)


The pre-class survey is available at x


# Course Information
**Title:** Working with Scholarly Literature in R: Pulling, Wrangling, Cleaning, and Analyzing Structured Bibliographic Metadata

**Instructor:**
Clarke Iakovakis, Scholarly Services Librarian, Oklahoma State University, <https://info.library.okstate.edu/clarke-iakovakis>

**Website:** <https://ciakovx.github.io/fsci2020/fsci_syllabus2020.html>


# Description: 
Developers have created a number of packages for accessing the scholarly literature in R over the last several years, among them `rcrossref`, `rorcid`, and `roadoi.` These packages make use of the APIs in their systems to allow users to execute specific queries and pull the structured data into R, where it can be reshaped, merged with other data, and analyzed. This session will be based on the workshop I provided at last year's FSCI. The course will assume no experience with R; however, a thorough explanation of the R programming language will not be provided. 

The course will a mixture of pre-recorded videos and synchronous explanation and Question & Answer sessions. 

Students will access IPNYB (Jupyter Notebooks) files containing the scripts for the workshop, created with [binder](https://mybinder.org/). The files will include executable code alongside descriptions of what the code is doing. Students can therefore run code that has already been written, but will also write and execute their own R scripts within the Jupyter Notebooks environment. Students will access these notebooks while watching the videos explaining the code.

We will begin with a general orientation of the Jupyter Notebooks environment. We will then discuss R and provide a basic overview of how it works. This introduction will include reading data into R, installing packages, and some functions for cleaning and restructuring data. We will also discuss Crossref, ORCID, and Unpaywall, and the packages developed by the rOpenSci organization to access the API services of these organizations. 

We will then walk through `rcrossref`, `roadoi`, and `rorcid`.

* `rcrossref` interfaces with the CrossRef API, allowing users to pull article metadata based on ISSN, filter queries by publication date and license information, running queries by title and author, getting funder data, getting citation counts, and exporting to BibTeX, RIS, and CSV. This can be immensely powerful for collecting citation data, conducting literature reviews, creating bibliographies, and more.
* `roadoi` interfaces with Unpaywall, allowing users to input a set of DOIs and return publication information along with potential locations of open access versions.
* `rorcid` interfaces with the ORCID API, allowing users to pull publication data based on a specific ORCID iD, or to input names and other identifying information to find a specific individual’s identifier. 

As we work through the tutorials, students will continue to learn R functions for working with data, including `dplyr`, `purrr`, and `tidyr`. 

By the conclusion of the session, students will be able to work with and analyze data in R. On a deeper level, they will have more powerful tools for gathering subsets of the scholarly literature in clean and structured formats based on specific parameters. Because they will be walking away with executable scripts, they will be able to modify those and collect data based on parameters they are interested in. 

# Level: 
All levels

# Intended audience: 
This course is intended for scholarly communications librarians, repository managers, research funders, publishers, bibliometricians, and managers of Research Information Management Systems (RIMS).

# Requirements: 
Students will need a computer with internet access. It will not be necessary to download R or R Studio, as all code will be executed in Jupyter Notebooks in the browser, hosted by binder.

# Course Learning Objectives
A participant in this course will, at the end of the course, be able to:
- Use R to complete a range of data tasks, including understanding R syntax and data types, installing and loading packages, reading data from files and APIs, and executing functions for tidying and  analyzing data.
- Use the rorcid package in R to extract data from ORCID profiles, including authenticating with the ORCID API, finding ORCID iDs by name/affiliation, getting author biographical information, and getting works associated with individuals.
- Use the rcrossref and roadoi packages in R to extract data from the Crossref and Unpaywall database, including authenticating with the Crossref API, forming queries, getting publication information, getting data on articles, converting articles to BibTeX/RIS, getting citation data, and checking for open access versions.

# Course Topics
This course will cover these  topics:
- Introduction to R and RStudio
- Introduction to rorcid
- Introduction to rcrossref and roadoi


# Course Schedule

Following each Zoom session schedule, students will watch the videos and walk through the Jupyter Notebooks exercises.

**LIVE ZOOM SESSION SCHEDULE**
(All times Pacific)

Wednesday, Aug. 5
8-9AM: Introductory session
5-6PM: REPEAT Introductory session

Monday, Aug. 10
8-9AM: Actvity session 1
5-6PM: REPEAT Activity session 1

Wednesday, Aug. 12
8-9AM: Activity session 2
5-6PM: REPEAT Activity session 2

## Day 1 
Orientation to Jupyter Notebooks. Introduction to R/RStudio and its advantages over other data tools. Nuts and bolts of R syntax. Installing packages.
Using dplyr functions for data manipulation: renaming/recoding/selecting/creating variables, recoding values, ordering data.
Introduction to ORCID, the ORCID API, and rorcid. Authenticating rorcid in your R environment. Course outline at https://ciakovx.github.io/fsci2020/rorcid.html. 
Finding ORCID iDs by name, iD, email, and affiliation. Constructing queries.
Getting biographical metadata (date created, last modified, name, biography, email, keywords) and works metadata (type, title, publication date).

## Day 2
Recap of rorcid, answer outstanding questions.
Course outline at https://ciakovx.github.io/rcrossref.html. Introduction to Crossref, the Crossref API, and rcrossref. Authenticating rcrossref in your R environment.
Getting publication and article data by journal, keyword, and author. Constructing and filtering queries. Writing to CSV, BibTeX, and RIS.
Using roadoi to query the Unpaywall API for open access availability. Getting URLs and downloading full text.
Putting it all together: gathering IDs of authors affiliated at your university, harvesting their publications, determining funders, OA eligibility, and other questions
Course Materials and Supplies Required  
Students will need a laptop with internet access and an account with Microsoft Azure Notebooks at https://notebooks.azure.com/. 
Students will download the course code, data, and walkthrough PDFs from https://ciakovx.github.io/fsci_syllabus.html. We will do this together during the class.

# Other Resources
If students have time, it is recommended to install and work through the swirl package in R at https://swirlstats.com/students.html. This will give them a good introduction to R and RStudio.
R cheat sheets
base R cheat sheet
purrr cheat sheet
data transformation cheat sheet
data import cheat sheet

